import Head from "next/head";
import { Inter } from "next/font/google";

import Navigation from "@/components/navigation";
import { Mainhero } from "@/components/Mainhero";
import { ambilIdentitas } from "@/lib/dashboardApi";
import { Organized } from "@/components/organized";
import { About } from "@/components/about";
import { Process } from "@/components/process";
import Services from "@/components/services";
import Afterevent from "@/components/afterevent";
import Contact from '@/components/contact';
import { Footer } from "@/components/footer";
import { Timevenue } from "@/components/timevenue";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ identitas }) {
  return (
    <>
      <Head>
        <title>GYIIF OFFICIAL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navigation />
      <Mainhero identitas={identitas} />
      <Organized />
      <About />
      {/* <Timevenue /> */}
      <Process />
      <Services />
      <Afterevent />
      <Contact />
      <Footer />
    </>
  );
}

/**
 * Identitas edisi ditarik saat halaman dibangun ulang, bukan tiap kunjungan.
 *
 * Lima menit, sama dengan umur cache API-nya — tidak ada permintaan yang
 * terbuang menanyakan sesuatu yang di sana pun masih disimpan.
 */
export async function getStaticProps() {
  return {
    props: { identitas: await ambilIdentitas() },
    revalidate: 300,
  };
}
