import Head from "next/head";
import { Inter } from "next/font/google";

import Navigation from "@/components/navigation";
import { Faq } from "@/components/faq";
import { Footer } from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export default function pagefaq({ data }) {
  return (
    <>
      <Head>
        <title>NYIIF OFFICIAL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navigation />
      <Faq />
      <Footer />
    </>
  );
}